# This workflow will Docker Build the app and push to GitHub and Google Cloud's Container Repositories.
# Then it will push the latest build to Google Kubernates Engine.

name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.MD
      - LICENSE.md
      - .gitignore
      - .github/**
      - '!.github/workflows/build.yml'
  release:
    tags:
      - v*.*.*
    types: [published]
  workflow_dispatch:

jobs:
  Build_and_Push:
    runs-on: ubuntu-latest
    steps:

    - name: Set Tag to Commit SHA
      if: endsWith(github.ref, '/main')
      run: |
        echo "TAG=${{ github.sha }}" >> $GITHUB_ENV
        echo "SECRET_VERSION=latest" >> $GITHUB_ENV

    - name: Set TAG to Version
      if: github.event_name == 'release'
      run: |
        echo "TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
        echo "SECRET_VERSION=latest" >> $GITHUB_ENV

    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}

    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.GCLOUD_AUTH }}

    - name: Authorize Docker push
      run: gcloud auth configure-docker

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v3
      with:
          push: true
          tags: |
            ghcr.io/hyperclaw79/pokegambler:${{ env.TAG }}
            gcr.io/pokegambler/pokegambler:${{ env.TAG }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  GKE_Deploy:
    runs-on: ubuntu-latest
    needs: [Build_and_Push]
    steps:

    - name: Set Tag to Commit SHA
      if: endsWith(github.ref, '/main')
      run: |
        echo "TAG=${{ github.sha }}" >> $GITHUB_ENV
        echo "SECRET_VERSION=latest" >> $GITHUB_ENV
        echo "FOLDER=prod" >> $GITHUB_ENV
        echo "IS_PROD=True" >> $GITHUB_ENV

    - name: Set TAG to Version
      if: github.event_name == 'release'
      run: |
        echo "TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
        echo "SECRET_VERSION=latest" >> $GITHUB_ENV
        echo "FOLDER=prod" >> $GITHUB_ENV
        echo "IS_PROD=True" >> $GITHUB_ENV

    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.GCLOUD_AUTH }}
        export_default_credentials: true

    - name: Authorize Docker push
      run: gcloud auth configure-docker

    - name: Get GKE Credentials
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: pokegambler-cluster
        location: us-central1-c

    - name: Set up Kustomize
      run: |-
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
        chmod u+x ./kustomize

    - name: Prepare Secret
      run: |-
        cd deployments/${{ env.FOLDER}}
        kubectl delete secret pokegambler-${{ env.FOLDER }} --ignore-not-found
        kubectl create secret generic pokegambler-${{ env.FOLDER }} \
          --from-literal=TOKEN=${{ secrets.TOKEN }} \
          --from-literal=IS_PROD=${{ env.IS_PROD }} \
          --from-literal=DISCORD_WEBHOOK_CHANNEL=${{ secrets.DISCORD_WEBHOOK_CHANNEL }} \
          --from-literal=DISCORD_WEBHOOK_TOKEN=${{ secrets.DISCORD_WEBHOOK_TOKEN }} \
          --from-literal=TOPGG_TOKEN=${{ secrets.TOPGG_TOKEN }} \
          --from-literal=OFFICIAL_SERVER=${{ secrets.OFFICIAL_SERVER }} \
          --from-literal=ADMIN_CMD_LOG_CHANNEL=${{ secrets.ADMIN_CMD_LOG_CHANNEL }} \
          --from-literal=ANNOUNCEMENT_CHANNEL=${{ secrets.ANNOUNCEMENT_CHANNEL }} \
          --from-literal=ERROR_LOG_CHANNEL=${{ secrets.ERROR_LOG_CHANNEL }} \
          --from-literal=IMG_UPLOAD_CHANNEL=${{ secrets.IMG_UPLOAD_CHANNEL }} \
          --from-literal=OWNER_ID=${{ secrets.OWNER_ID }} \
          --from-literal=ALLOWED_USERS='${{ secrets.ALLOWED_USERS }}' \
          --from-literal=DEFAULT_GUILDMODE=${{ secrets.DEFAULT_GUILDMODE }} \
          --from-literal=BLACKLIST_GUILDS='${{ secrets.BLACKLIST_GUILDS }}' \
          --from-literal=WHITELIST_GUILDS='${{ secrets.WHITELIST_GUILDS }}' \
          --from-literal=MONGO_CLUSTER_STRING='${{ secrets.MONGO_CLUSTER_STRING }}'

    - name: Send Restart Webhook to Discord
      continue-on-error: true
      env:
        COMMITS: ${{ toJSON(github.event.commits) }}
      run: |-
        changes=$(
          echo $COMMITS \
          | jq -r '.[] | select(.message | startswith("[Update]")) | .message' \
          | awk '{printf "%d. %s\\n", NR, $s}' \
          | sed "s/\[Update\]//g"
        )
        changelog=$([[ $changes ]] && echo \`\`\`md$"\n"# Changelog"\n"$changes\`\`\` || echo "")
        curl -X POST 'https://discord.com/api/webhooks/${{ secrets.DISCORD_WEBHOOK_CHANNEL }}/${{ secrets.DISCORD_WEBHOOK_TOKEN }}' \
        -H 'Content-Type: application/json' \
        -d '{"content": "<:update:874626019846402110>\t**Restart Initiated**\nPokeGambler will be updating now.\n\u200b'"$changelog"'\n\u200b\n", "username": "PokeGambler Status Monitor"}'

    - name: Deploy to GKE
      run: |-
        cd deployments/${{ env.FOLDER }}
        ../../kustomize edit add annotation commit_sha:${{ github.sha }} --force
        ../../kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/pokegambler/pokegambler:${{ env.TAG }}
        ../../kustomize build . | kubectl apply -f -
        kubectl rollout status deployment/pokegambler-${{ env.FOLDER }}
        kubectl get services -o wide
