# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Lint & Style Check

on:
  push:
    paths-ignore:
      - README.md
      - LICENSE.md
      - .gitignore
      - .github/**
  workflow_dispatch:

jobs:
  Lint_Styler:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.x'
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pycodestyle
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Code Style Checks
      run: |
        pycodestyle --max-line-length=85 scripts bot.py launcher.py
    - name: Run Linting
      run: |
        pylint -f colorized scripts bot.py launcher.py
