apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokegambler-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokegambler-prod
  template:
    metadata:
      labels:
        app: pokegambler-prod
    spec:
      containers:
      - name: app
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: pokegambler-prod
